apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: secret-patch.yaml
    target:
      kind: Secret
      name: relay-auth

patchesStrategicMerge:
  - deployment-patch.yaml
