---

name: publish-tag

on:
  create:
    tags:
      - v*

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: randomgoods/alertmanager-relay
          registry: docker.io
          tags: ${{ env.RELEASE_VERSION }}, stable
          dockerfile: ./Dockerfile
          directory: .
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

...
